openapi: 3.0.2
info:
    title: Cars-API
    version: 1.0.0
    description: '### This is a Swagger UI for our Car API'
paths:
    /locations:
        get:
            tags:
                - Locations
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                List of locations:
                                    value:
                                        -
                                            LocationID: '1'
                                            City: Tallinn
                                            Country: Estonia
                                        -
                                            LocationID: '2'
                                            City: Berlin
                                            Country: Germany
                                        -
                                            LocationID: '3'
                                            City: Moscow
                                            Country: Russia
                    description: Returns a list of al locations
            summary: List of Locations
            description: |
                Returns a list of all locations
    /sellers:
        get:
            tags:
                - Sellers
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                List of sellers:
                                    value:
                                        -
                                            SellerID: '1'
                                            Name: Martin
                                            Email: martinhobesalu@gmail.com
                                            Phone: '98347561'
                                        -
                                            SellerID: '2'
                                            Name: Kaarel
                                            Email: kaarelnoole@gmail.com
                                            Phone: '63276615'
                    description: Returns a list of sellers
            summary: Get a List of sellers
            description: |
                Returns a list of sellers
    /prices:
        get:
            tags:
                - prices
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                List of Prices:
                                    value:
                                        -
                                            PriceID: '1'
                                            Amount: '3000'
                                            Currency: $
                                        -
                                            BrandID: '2'
                                            Amount: '5000'
                                            Currency: £
                                        -
                                            PriceID: '3'
                                            Amount: '4000'
                                            Currency: €
                    description: Returns a list of prices
            summary: Get a list of all prices
            description: Returns a list of all prices in API
    /models:
        get:
            tags:
                - models
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items: {}
                            examples:
                                List of car models:
                                    value:
                                        -
                                            ModelID: '1'
                                            Name: Ford focus
                                            Color: Grey
                                            BrandID: '1'
                                        -
                                            ModelID: '2'
                                            Name: Model S
                                            Color: Black
                                            BrandID: '2'
                                        -
                                            ModelID: '3'
                                            Name: Yaris
                                            Color: Red
                                            BrandID: '3'
                    description: Returns a list of car models
            summary: Get a list of all car models
            description: |
                Returns a list of all car models in API
    /brands:
        get:
            tags:
                - brands
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items: {}
                            examples:
                                List of car brands:
                                    value:
                                        -
                                            BrandID: '1'
                                            Name: Ford
                                            Origin: Germany
                                        -
                                            BrandID: '2'
                                            Name: Tesla
                                            Origin: USA
                                        -
                                            BrandID: '3'
                                            Name: Toyota
                                            Origin: Japan
                    description: |
                        Returns a list of car brands
            summary: Get a list of all car brands
            description: Returns a list of all car brands in API
    '/brands/{id}':
        get:
            tags:
                - details
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                Full details of a given brand:
                                    value: '{id: 2, Brand: ''Tesla'', origin: ''USA''},'
                    description: |
                        Returns full details of a given id brand
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                error:
                                    value:
                                        error: brand not found
                    description: Brand was not found in brand array
            deprecated: false
            operationId: id
            summary: Get full details of a brand
            description: |
                Retruns full details of a given id brand
components:
    schemas:
        error:
            title: Root Type for error
            description: ''
            type: object
            properties:
                error:
                    type: string
            example:
                error: Error message